# Generated by Django 2.0.1 on 2018-02-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_test'),
        ('accounts', '0003_auto_20180205_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joinedCourses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product'),
        ),
    ]
