# Generated by Django 2.0.1 on 2018-02-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_joinedcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joinedCourses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product'),
        ),
    ]
