# Generated by Django 2.0.1 on 2018-02-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_test'),
        ('accounts', '0005_auto_20180205_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joinedCourses',
        ),
        migrations.AddField(
            model_name='user',
            name='joinedCourses',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
