# Generated by Django 2.0.1 on 2018-02-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180205_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='joinedCourses',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
