# Generated by Django 2.0.4 on 2018-04-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180428_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instructor',
            new_name='staff',
        ),
    ]
