# Generated by Django 2.0.4 on 2018-04-28 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_test'),
        ('accounts', '0013_auto_20180428_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instrCourse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='products.Product'),
        ),
    ]
