# Generated by Django 2.0.4 on 2018-04-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_instrcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instructor',
            field=models.BooleanField(default=True),
        ),
    ]
