# Generated by Django 2.0 on 2018-01-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, null=True)),
                ('courseUrl', models.CharField(max_length=220, null=True)),
                ('duration', models.CharField(max_length=120, null=True)),
                ('image', models.TextField(null=True)),
                ('name', models.CharField(default='defaultCourse', max_length=120)),
                ('price', models.CharField(max_length=120, null=True)),
                ('promoMediaUrl', models.TextField(null=True)),
                ('startDate', models.CharField(max_length=120, null=True)),
                ('summary', models.TextField(null=True)),
                ('type', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
