# Generated by Django 2.0.1 on 2018-01-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instructorFullName',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instructorImageUrl',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instructorProfileUrl',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
