# Generated by Django 2.0.1 on 2018-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180130_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='courseUrl',
            field=models.CharField(default='NotExist', max_length=220),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.CharField(default='10 weeks', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(default='NotExist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='instructorFullName',
            field=models.CharField(default='NotExist', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='instructorImageUrl',
            field=models.CharField(default='NotExist', max_length=220),
        ),
        migrations.AlterField(
            model_name='product',
            name='instructorProfileUrl',
            field=models.CharField(default='NotExist', max_length=220),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='10 AUD', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='promoMediaUrl',
            field=models.TextField(default='NotExist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='startDate',
            field=models.CharField(default='15 Dec 2017', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='NotExist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='free', max_length=120),
        ),
    ]
