# Generated by Django 2.0.1 on 2018-02-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180201_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='startDate',
            field=models.CharField(default='15 Dec 2017', max_length=120, null=True),
        ),
    ]
