# Generated by Django 2.0.1 on 2018-02-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
