# Generated by Django 2.0.4 on 2018-04-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180428_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='course_id',
            field=models.ForeignKey(default=350, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
