# Generated by Django 2.0.4 on 2018-04-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180428_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='course_id',
            field=models.ForeignKey(blank=True, default=350, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
