# Generated by Django 2.0.4 on 2018-04-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180428_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='data',
        ),
        migrations.AlterField(
            model_name='document',
            name='course_id',
            field=models.ForeignKey(blank=True, default=850, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
