# Generated by Django 2.0.4 on 2018-04-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180428_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='course_id',
        ),
        migrations.AddField(
            model_name='document',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Doc_id',
            field=models.ForeignKey(blank=True, default=850, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Document'),
        ),
    ]
