# Generated by Django 2.0.4 on 2018-04-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180428_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Doc_id',
        ),
    ]
